[project]
name = "auto-example-env"
version = "1.0.0"
description = "Generate example.env from .env file for documentation purposes"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
auto-example-env = "main:main"

[tool.setuptools]
py-modules = ["main"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
commit_message = "chore(release): bump version to {version}"
build_command = """
    python -m pip install build
    python -m build
"""
